config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :expenses, only: %i[index edit update new create destroy]
  get 'expenses/approve', to: 'expenses#approval_queue'
  post 'expenses/:id/approve', to: 'expenses#approve', as: :approve_expense
  post 'expenses/:id/deny', to: 'expenses#deny', as: :deny_expense

  resources :users, only: %i[index edit update]
  resources :teams

  get 'auth/login'
  get 'auth/logout'
  get 'auth/callback'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'expenses#index'
end

app/controllers/expenses_controller.rb
# frozen_string_literal: true

class ExpensesController < ApplicationController
  include Authorization

  before_action :check_manager_authz, only: %i[approval_queue approve deny]

  def index
    @expenses = @authenticated_user&.expenses || []
  end

  def new
    @expense = Expense.new
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def create
    Expense.transaction do
      @expense = Expense.new(expense_params)
      @expense.user_id = @authenticated_user.id
      @expense.save

      # Create the relationship in FGA
      associate_user_to_expense(user_id: @expense.user_id, expense_id: @expense.id)

      # If this user has no manager, go straight to finance for approval
      if @authenticated_user.manager_id.nil?
        Team.where(expense_approver: true).find_each do |dep|
          associate_team_to_expense(team_id: dep.id, expense_id: @expense.id)
        end

        @expense.update(status: :manager_approved)
      end
    end

    if @expense.valid?
      redirect_to expenses_path
    else
      render :new
    end
  end

  def update
    expense = Expense.find(params[:id])
    expense.update(expense_params)

    if expense.valid?
      redirect_to expenses_path
    else
      render :edit
    end
  end

  def destroy
    Expense.transaction do
      expense = Expense.find(params[:id])
      expense.delete

      # Remove from the FGA store
      remove_expense(expense_id: expense.id)
    end
    redirect_to expenses_path
  end

  # Displays the approval queue for expenses. Managers only.
  def approval_queue
    @expenses = Expense.where(
      id: expense_approvals_for(user_id: @authenticated_user.id),
      status: %i[submitted manager_approved]
    )
  end

  def approve
    expense = Expense.find(params[:id])

    if expense.nil?
      respond_to do |format|
        format.html { redirect_to expenses_approve_path, notice: 'Expense not found.' }
        format.json { render json: { error: 'Expense not found.' }, status: :not_found }
      end
    end

    next_status = case expense.status.to_sym
                  when :submitted
                    :manager_approved
                  when :manager_approved
                    :approved
                  end

    expense.transaction do
      # Just automatically approve if the user is an expense approver
      next_status = :approved if @authenticated_user.team.expense_approver?
      expense.update(status: next_status)

      # If this team can approve expenses, remove the team from the expense in FGA since this is the last stage
      if @authenticated_user.team.expense_approver?
        begin
          disassociate_team_from_expense(team_id: @authenticated_user.team_id, expense_id: expense.id)
        rescue StandardError
        end
      else
        # Add the teams who can approve to this expense in FGA
        Team.where(expense_approver: true).find_each do |dep|
          associate_team_to_expense(team_id: dep.id, expense_id: expense.id)
        end
      end
    end

    redirect_to expenses_approve_path
  end

  def deny
    Expense.update(params[:id], status: :rejected)

    redirect_to expenses_approve_path
  end

  private

  def expense_params
    params.require(:expense).permit(:amount, :description)
  end

  def check_manager_authz
    head :unauthorized unless @authenticated_user.role == 'manager' || @authenticated_user.team.expense_approver?
  end
end

app/helpers/expenses_helper.rb
# frozen_string_literal: true

module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%
  input_classes = "p-2 rounded-lg border border-grey-300 focus:outline-blue-500 text-gray-800"
  label_classes = "block mb-2 text-gray-800 text-sm"
%>

<div class="w-1/2 mx-auto">
  <%= form_with model: @expense do |form| %>
    <div class="border-b border-gray-200 mb-5">
      <div class="mb-5">
        <%= form.label :amount, 'Amount:', class: label_classes %>
        <%= form.number_field :amount, class: input_classes, placeholder: '0.00', required: true %>
      </div>
      <div class="mb-5">
        <%= form.label :description, 'Description:', class: label_classes %>
        <%= form.text_area :description, class: input_classes, rows: 3, cols: 30, placeholder: 'Describe the expense..', required: true %>
      </div>
    </div>

    <div class="flex items-center">
      <div class="grow">
        <strong>Status:</strong>
        <%= @expense.new_record? ? 'New' : expense_status(@expense.status) %>
      </div>
      <div class="flex">
        <% unless @expense.new_record? %>
          <%= link_to 'Delete', @expense, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'p-2 mr-1 rounded text-gray-500 bg-gray-100' %>
        <% end %>
        <%= form.submit 'Save', class: 'p-2 rounded text-white bg-blue-500' %>
      </div>
    </div>
  <% end %>
</div>

app/views/expenses/approval_queue.html.erb
<h1 class="text-3xl text-gray-500 font-light mb-10">Approval queue</h1>

<% unless @expenses.any? %>
  <div class="bg-gray-100 p-5 py-20 rounded-lg text-center text-gray-500">
    There are no expenses to approve.
  </div>
<% else %>
  <div class="rounded-lg overflow-auto bg-gray-100">
    <table class="table-auto w-full mt-5 border-collapse">
      <thead>
        <tr>
        <th class="<%= default_table_header_classes %>">Id</th>
        <th class="<%= default_table_header_classes %>">Raised by</th>
        <th class="<%= default_table_header_classes %>">Amount</th>
        <th class="<%= default_table_header_classes %>">Description</th>
        <th class="<%= default_table_header_classes %>">Status</th>
        <th class="<%= default_table_header_classes %>">Created</th>
        <th class="<%= default_table_header_classes %>">Actions</th>
        </tr>
      </thead>
      </thead>
      <tbody class="bg-white">
        <% @expenses.each do |expense| %>
          <tr>
            <td class="<%= default_table_header_classes %>"><%= expense.id %></td>
            <td class="<%= default_table_row_classes %>"><%= expense.user.name %></td>
            <td class="<%= default_table_row_classes %>"><%= number_to_currency(expense.amount) %></td>
            <td class="<%= default_table_row_classes %>"><%= expense.description %></td>
            <td class="<%= default_table_row_classes %>">
              <span class="flex items-center">
                <span class="w-6 mr-2"><%= status_icon(expense.status) %></span>
                <%= expense_status(expense.status) %></td>
              </span>
            </td>
            <td class="<%= default_table_row_classes %>"><%= time_ago_in_words(expense.created_at) %> ago</td>
            <td class="<%= default_table_row_classes %>">
              <% if show_approve_buttons?(expense) %>
                <%= link_to 'Approve', approve_expense_path(expense.id), data: { turbo_method: :post }, class: 'p-2 mr-3 bg-lime-300 text-lime-700 shadow rounded' %>
                <%= link_to 'Deny', deny_expense_path(expense.id), data: { turbo_method: :post }, class: 'p-2 mr-3 bg-slate-300 text-slate-700 shadow rounded' %>
              <% end %>
            </td>
          </tr>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

app/views/expenses/edit.html.erb
<h1 class="text-2xl mb-5">Edit expense</h1>

<%= render 'form' %>

app/views/expenses/index.html.erb
<div class="flex items-center mb-10">
  <h1 class="text-3xl text-gray-500 font-light mr-5">My expenses</h1>
  <div class="p-2 bg-gray-100 text-gray-500 shadow rounded flex items-center">
    <span class="mr-4 w-3"><%= icon 'plus-circle' %></span>
    <%= link_to 'Create', new_expense_path, class: 'block' %>
  </div>
</div>

<% if @expenses.any? %>
  <div class="rounded-lg overflow-auto bg-gray-100">
    <table class="table-auto w-full mt-5 border-collapse">
      <thead>
        <tr>
        <th class="<%= default_table_header_classes %>">Id</th>
        <th class="<%= default_table_header_classes %>">Amount</th>
        <th class="<%= default_table_header_classes %>">Description</th>
        <th class="<%= default_table_header_classes %>">Status</th>
        <th class="<%= default_table_header_classes %>">Created</th>
        <th class="<%= default_table_header_classes %>">Actions</th>
        </tr>
      </thead>
      </thead>
      <tbody class="bg-white">
        <% @expenses.each do |expense| %>
          <tr>
            <th class="<%= default_table_header_classes %>"><%= expense.id %></th>
            <td class="<%= default_table_row_classes %>"><%= number_to_currency(expense.amount) %></td>
            <td class="<%= default_table_row_classes %>"><%= expense.description %></td>
            <td class="<%= default_table_row_classes %>">
              <span class="flex items-center">
                <span class="w-6 mr-2"><%= status_icon(expense.status) %></span>
                <%= expense_status(expense.status) %></td>
              </span>
            <td class="<%= default_table_row_classes %>"><%= time_ago_in_words(expense.created_at) %> ago</td>
            <td class="<%= default_table_row_classes %>">
              <%= link_to 'Edit', edit_expense_path(expense.id), class: 'p-2 mr-3 bg-gray-100 text-slate-500 shadow rounded' %>
            </td>
          </tr>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="bg-gray-100 p-5 py-20 rounded-lg text-center text-gray-500">
    You don't have any expenses yet!
  </div>
<% end %>

app/views/expenses/new.html.erb
<h1 class="text-3xl mb-10 font-light text-gray-500">New expense</h1>

<%= render 'form' %>

app/views/expenses/update.html.erb
<h1>Expenses#update</h1>
<p>Find me in app/views/expenses/update.html.erb</p>