config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :expenses, only: %i[index edit update new create destroy]
  get 'expenses/approve', to: 'expenses#approval_queue'
  post 'expenses/:id/approve', to: 'expenses#approve', as: :approve_expense
  post 'expenses/:id/deny', to: 'expenses#deny', as: :deny_expense

  resources :users, only: %i[index edit update]
  resources :teams

  get 'auth/login'
  get 'auth/logout'
  get 'auth/callback'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'expenses#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Authentication
  include Authorization

  before_action :check_session

  private

  def check_session
    return do_login unless logged_in?

    sub = user_session
    @authenticated_user = User.preload(:team).find_by(sub:)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def default_table_row_classes
    'px-3 py-4 text-left text-sm font-normal text-gray-600 border-b border-gray-100'
  end

  def default_table_header_classes
    'p-3 text-left text-sm font-medium text-gray-500 border-b border-gray-200'
  end

  def expense_status(status)
    case status
    when 'submitted'
      'Submitted, awaiting manager approval'
    when 'manager_approved'
      'Approved by manager, pending finance sign-off'
    when 'approved'
      'Approved'
    when 'rejected'
      'Rejected'
    end
  end

  def status_icon(status)
    case status.to_sym
    when :submitted
      content_tag :span, icon('chevron-up'), class: 'text-cyan-600'
    when :manager_approved
      content_tag :span, icon('chevron-double-up'), class: 'text-blue-600'
    when :approved
      content_tag :span, icon('check-circle'), class: 'text-green-600'
    when :rejected
      content_tag :span, icon('x-circle'), class: 'text-red-600'
    end
  end

  def show_approve_buttons?(expense)
    (@authenticated_user.team.expense_approver? && expense.status.to_sym == :manager_approved) ||
      (@authenticated_user.role.to_sym == :manager && expense.status.to_sym == :submitted)
  end
end

app/views/application/_header.html.erb
<div class="bg-slate-800 text-white p-10 pb-6 mb-10">
  <div class="flex container mx-auto">
    <div class="grow flex">
      <h1><%= link_to 'WorkNight', root_path, class: 'font-bold mr-5' %></h1>
      <span class="mr-5 font-bold">|</span>
      <% if @authenticated_user.role == 'manager' || @authenticated_user.team&.expense_approver? %>
        <%= link_to 'Approval queue', expenses_approve_path, class: 'block mr-3' %>
      <% end %>
      <%= link_to 'My expenses', expenses_path, class: 'block mr-3' %>
      <%= link_to 'Users', users_path, class: 'block mr-3' %>
      <%= link_to 'Teams', teams_path, class: 'block' %>
    </div>
    <div class="flex items-center">
      <div class="flex">
        <div class="mr-5 flex flex-col">
          <div>Logged in as <%= @authenticated_user.name %></div>
          <div class="text-right text-xs text-slate-400 uppercase"><%= @authenticated_user.team&.name %></div>
        </div>
        <div>
          <%= link_to 'logout', auth_logout_path, data: { turbo_prefetch: false, turbo: false } %>
        </div>
      </div>
    </div>
  </div>
</div>